version: '3'
services:
  app:
    build: .
    container_name: todo_app
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0
    container_name: todo_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
